### ISSUE TITLE
log excerpt does not display on php 7.1.4

### ISSUE THREAD

**Issue by torvista** [lat9/display_logs#11]
no debug is created, just
`<div id="fContents"></div>`
is empty

**Comment by lat9** [comment]
Thanks for the report!  I'll see what's up.

**Comment by lat9** [comment]
Oh my!  I've (currently) got the parameters for the `file_get_contents` call **very** messed up.  Let me get that source "re-factored" and then get the change in.

**Comment by lat9** [comment]
Correction now complete; it'll be released as part of v2.0.1.
