### ISSUE TITLE
ZC157: debug undefined variable $current_page

### ISSUE THREAD

**Issue by torvista** [lat9/display_logs#15]
during install and subsequently:

> [12-Feb-2020 10:21:12 Europe/Madrid] Request URI: /zencart-157/admin1/index.php?cmd=specials, IP address: 127.0.0.1
#1  require(...\zencart-157\includes\autoload_func.php) called at [...\zencart-157\admin1\includes\application_top.php:36]
#2  require(...\zencart-157\admin1\includes\application_top.php) called at [...\zencart-157\admin1\specials.php:9]
#3  require(...\zencart-157\admin1\specials.php) called at [...\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined index: messageStack in ...\zencart-157\includes\autoload_func.php on line 47.

[12-Feb-2020 10:21:12 Europe/Madrid] Request URI: /zencart-157/admin1/index.php?cmd=specials, IP address: 127.0.0.1
#1  require(...\zencart-157\includes\autoload_func.php) called at [...\zencart-157\admin1\includes\application_top.php:36]
#2  require(...\zencart-157\admin1\includes\application_top.php) called at [...\zencart-157\admin1\specials.php:9]
#3  require(...\zencart-157\admin1\specials.php) called at [...\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined index: messageStack in ...\zencart-157\includes\autoload_func.php on line 50.

[12-Feb-2020 10:21:12 Europe/Madrid] Request URI: /zencart-157/admin1/index.php?cmd=specials, IP address: 127.0.0.1
#1  require(...\zencart-157\admin1\includes\init_includes\init_display_logs.php) called at [...\zencart-157\includes\autoload_func.php:27]
#2  require(...\zencart-157\includes\autoload_func.php) called at [...\zencart-157\admin1\includes\application_top.php:36]
#3  require(...\zencart-157\admin1\includes\application_top.php) called at [...\zencart-157\admin1\specials.php:9]
#4  require(...\zencart-157\admin1\specials.php) called at [...\zencart-157\admin1\index.php:11]
--> PHP Notice: Undefined variable: current_page in ...\zencart-157\admin1\includes\init_includes\init_display_logs.php on line 59.

**Comment by torvista** [comment]
https://github.com/zencart/zencart/issues/3061#issue-563917068

**Comment by lat9** [comment]
Noting that that's a behavioral change in zc157; they'll need to fix the issue there for backward compatibility.

**Comment by lat9** [comment]
New zencart issue opened: https://github.com/zencart/zencart/issues/3073

**Comment by lat9** [comment]
@torvista, with a freshly downloaded blob from the zc157 branch and "Display Logs" v2.2.0, I'm not seeing that log anymore.  What's different with your setup?

**Comment by torvista** [comment]
Dunno. I'm using ZC157 'now' and 2.2.0 and get this on every refresh:

> [06-Mar-2020 14:54:37 Europe/Madrid] Request URI: /zencart-157/admin1/, IP address: 127.0.0.1
> #1  require(...\public_html\zencart-157\admin1\includes\init_includes\init_display_logs.php) called at [...\public_html\zencart-157\includes\autoload_func.php:27]
> #2  require(...\public_html\zencart-157\includes\autoload_func.php) called at [...\public_html\zencart-157\admin1\includes\application_top.php:36]
> #3  require(...\public_html\zencart-157\admin1\includes\application_top.php) called at [...\public_html\zencart-157\admin1\home.php:10]
> #4  require(...\public_html\zencart-157\admin1\home.php) called at [...\public_html\zencart-157\admin1\index.php:11]
> --> PHP Notice: Undefined variable: current_page in ...\public_html\zencart-157\admin1\includes\init_includes\init_display_logs.php on line 59.

fileset is here:
https://www.dropbox.com/s/xjgradawv1663ea/zencart-157.7z?dl=1

**Comment by lat9** [comment]
Noting that the fileset supplied doesn't include the zc157 update to /admin/includes/init_includes/init_languages.php that corrects that issue in the core.

**Comment by torvista** [comment]
Dammit, I knew that was the file in question but the old and new have
exactly the same filesize so Beyond Compare did not flag it up....I don't
use the repository directly...
